/*
 *
 * TreeMap constants
 *
 */

//  For Advance Decline Data
export const LOAD_ADVANCE_DECLINE_DATA = 'app/TreeMap/LOAD_ADVANCE_DECLINE_DATA';
export const LOAD_ADVANCE_DECLINE_DATA_SUCCESS = 'app/TreeMap/LOAD_ADVANCE_DECLINE_DATA_SUCCESS';
export const LOAD_ADVANCE_DECLINE_DATA_ERROR = 'app/TreeMap/LOAD_ADVANCE_DECLINE_DATA_ERROR';

//  For Advance Decline 4 Data
export const LOAD_ADVANCE_DECLINE_4_DATA = 'app/TreeMap/LOAD_ADVANCE_DECLINE_4_DATA';
export const LOAD_ADVANCE_DECLINE_4_DATA_SUCCESS = 'app/TreeMap/LOAD_ADVANCE_DECLINE_4_DATA_SUCCESS';
export const LOAD_ADVANCE_DECLINE_4_DATA_ERROR = 'app/TreeMap/LOAD_ADVANCE_DECLINE_4_DATA_ERROR';

//  For TreeMap Data
export const LOAD_TREEMAP_DATA = 'app/TreeMap/LOAD_TREEMAP_DATA';
export const LOAD_TREEMAP_DATA_SUCCESS = 'app/TreeMap/LOAD_TREEMAP_DATA_SUCCESS';
export const LOAD_TREEMAP_DATA_ERROR = 'app/TreeMap/LOAD_TREEMAP_DATA_ERROR';